### ISSUE TITLE
Error using this keyboard with an EditText that has a currency formatting TextWatcher

### ISSUE THREAD

**Issue by chizoba** [konaire/NumericKeyboard#6]
When using a custom TextWatcher (which formats currency values based on locale), I run into this error **only when deleting** values.

```
java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1108)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:673)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:104)
        at com.konaire.numerickeyboard.util.KeyClickListener.onClick(KeyClickListener.kt:30)
        at android.view.View.performClick(View.java:5273)
        at android.view.View$PerformClick.run(View.java:21542)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5683)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

For example, I input `1234` which due to the TextWatcher becomes `1,234`. On pressing the delete button, it becomes `123`, but `previousChar` in the code will have a value of `4` instead of `3`. Hence, when `field.setSelection(previousChar)`, it throws that error. 

I have a fix for this, which I have done, and I am requesting your permission to send a PR.

Cheers!

**Comment by konaire** [comment]
Hey @chizoba. Thanks for using this library, that's great that you found a bug and fixed it. You should be able to push your PR, someone did it already before 👍

**Comment by konaire** [comment]
Fixed in [this release](https://github.com/konaire/NumericKeyboard/releases/tag/1.1.0).
